// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck

import type { Metadata, Viewport } from 'next'
import { manrope } from '@/utils/fonts'
import './globals.scss'
import AppHeader, { AppHeaderNavLink } from '@/widgets/AppHeader'
import AppFooter from '@/widgets/AppFooter'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  colorScheme: 'only light',
  themeColor: 'white',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  interactiveWidget: 'resizes-visual',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={[manrope.className, 'overflow-hidden overflow-y-auto scroll-smooth snap-y snap-mandatory w-full max-w-full min-h-screen bg-white text-black fill-black antialiased'].filter((n) => n).join(' ')}
      >
        <AppHeader>
          <AppHeaderNavLink
            label='Select'
            href='/#select'
          />
          <AppHeaderNavLink
            label='Deliver'
            href='/#deliver'
          />
          <AppHeaderNavLink
            label='Install'
            href='/#install'
          />
        </AppHeader>
        <div className='overflow-hidden overflow-y-auto scroll-smooth snap-y snap-mandatory w-full max-w-full max-h-screen'>
          {children}
          <AppFooter />
        </div>
      </body>
    </html>
  )
}
