import type { Metadata, Viewport } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export const viewport: Viewport = {
    colorScheme: 'only light',
    themeColor: 'white',
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
    interactiveWidget: 'resizes-visual',
} 